// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhqooxxofqoqfpmidluu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJocW9veHhvZnFvcWZwbWlkbHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTIyNzQsImV4cCI6MjA2OTk2ODI3NH0.-c3MbvNxwUllnhhFc4dts5bTYFaIKXbFnSS0V78jC_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});